In [ ]:
'''
Aaron Chen
aaron.chen@spc.ox.ac.uk

Collect data from scraped company_status json files. Returns and saves a dataframe with company status information and SIC code. 
'''

In [1]:
import pandas as pd
import glob
from tqdm import tqdm
import json

In [2]:
company_id = set([i.split('/')[-2] for i in glob.glob('data/*/*') if 'company_status' in i])

In [3]:
len(company_id)

1452959

In [4]:
officer_status = []
for c in tqdm(company_id):
    info = json.loads(open(f'data/{c}/company_status.json').read())
    status={}
    status['company_status'] = info.get('company_status', 'no_info')
    status['CompanyName'] = info.get('company_name', 'no_info')
    status['CompanyNumber'] = info.get('company_number', 'no_info')
    status['sic'] = info.get('sic_codes', 'no_info')
    status['has_insolvency_history']= info.get('has_insolvency_history', 'no_info')
    address = info.get('registered_office_address', {})
    status['registered_office_address'] = address.get('postal_code', 'no_info')
    status['type'] = info.get('type', 'no_info')
    status['has_been_liquidated'] = info.get('has_been_liquidated', 'no_info')
    status['date_of_creation'] = info.get('date_of_creation', 'no_info')
    
    officer_status.append(status)
    
officer_status_DF = pd.DataFrame(officer_status)

officer_status_DF

100%|█████████████████████████████████████████████████████████████████████| 1452959/1452959 [1:40:59<00:00, 239.77it/s]

,company_status,CompanyName,CompanyNumber,sic,has_insolvency_history,registered_office_address,type,has_been_liquidated,date_of_creation
0,active,CONTRACT SECURITY (UK) LTD,08264847,[80200],False,CM22 7TD,ltd,False,2012-10-23
1,active,"PASSER, CHEVERN & CO LTD",03939032,[74909],False,HA8 8JH,ltd,False,2000-03-03
2,active,MONTREUX INVESTMENTS LTD,13138637,[68209],False,LE4 6EG,ltd,no_info,2021-01-18
3,active,PSS TRADING LTD,SC639792,[56103],False,G77 6UT,ltd,no_info,2019-08-27
4,active,TAW HOLDINGS (UK) LIMITED,10569104,[98000],False,LE1 3RW,ltd,no_info,2017-01-17
...,...,...,...,...,...,...,...,...,...
1452954,active,J & MG HOLDINGS LTD,10111818,[68100],False,ME17 1TF,ltd,no_info,2016-04-08
1452955,active,VISUAL UK LIMITED,06253934,[47990],False,NR6 6EZ,ltd,False,2007-05-21
1452956,active,VAVOIN LTD,12500438,[82920],False,WR9 8AN,ltd,no_info,2020-03-05
1452957,active,MASTERCRAFT PROPERTY SOLUTIONS LIMITED,07979182,[42990],False,ME4 6AE,ltd,False,2012-03-07
1452958,dissolved,LOCALICIOUS LTD,11586984,[63120],False,HR3 6LG,ltd,no_info,2018-09-25

In [6]:
officer_status_DF = officer_status_DF.explode('sic')
officer_status_DF

,company_status,CompanyName,CompanyNumber,sic,has_insolvency_history,registered_office_address,type,has_been_liquidated,date_of_creation
0,active,CONTRACT SECURITY (UK) LTD,08264847,80200,False,CM22 7TD,ltd,False,2012-10-23
1,active,"PASSER, CHEVERN & CO LTD",03939032,74909,False,HA8 8JH,ltd,False,2000-03-03
2,active,MONTREUX INVESTMENTS LTD,13138637,68209,False,LE4 6EG,ltd,no_info,2021-01-18
3,active,PSS TRADING LTD,SC639792,56103,False,G77 6UT,ltd,no_info,2019-08-27
4,active,TAW HOLDINGS (UK) LIMITED,10569104,98000,False,LE1 3RW,ltd,no_info,2017-01-17
...,...,...,...,...,...,...,...,...,...
1452954,active,J & MG HOLDINGS LTD,10111818,68100,False,ME17 1TF,ltd,no_info,2016-04-08
1452955,active,VISUAL UK LIMITED,06253934,47990,False,NR6 6EZ,ltd,False,2007-05-21
1452956,active,VAVOIN LTD,12500438,82920,False,WR9 8AN,ltd,no_info,2020-03-05
1452957,active,MASTERCRAFT PROPERTY SOLUTIONS LIMITED,07979182,42990,False,ME4 6AE,ltd,False,2012-03-07
1452958,dissolved,LOCALICIOUS LTD,11586984,63120,False,HR3 6LG,ltd,no_info,2018-09-25

In [8]:
officer_status_DF.to_csv('SIC_list.csv', index=False)